FROM ubuntu
LABEL name="swapnil"
ENV NAME=grrass
ENV PASS=AWS
#RUN useradd -m -d /home/grrass -g root -G sudo -m -p $(echo "$PASS" | openssl passwd -l -stdin) $NAME

# run this after image build docker image inspect <image-name>
